import {SettlementStatus} from "@/components/settlement-status";
import {moneyText,totalCents} from "@/modules/settlements/schema";
import {notFound} from "next/navigation";
import {ReturnLink} from "@/components/context-link";
import {confirmedDetail} from "@/modules/settlements/queries";
import {dateRange} from "@/modules/live-reports/date-range";
import {SettlementForm,ConfirmedFields,Reason} from "@/components/settlement-forms";
import {formatDateTime} from "@/lib/datetime";
import {CorrectionHistory} from "@/components/work-corrections";
export default async function Page({params}:{params:Promise<{id:string}>}){
 const d=await confirmedDetail((await params).id);if(!d)notFound();const r=d.row;
 const labels:Record<string,string>={day:"日期",anchorName:"主播",backendName:"后端名称",backendUrl:"后端链接",joinCount:"加人数量",effectiveCount:"有效数量",backendUnitCents:"后端单价（分）",anchorUnitCents:"主播提成单价（分）",deletedAt:"删除时间",isSettled:"已结算",settledAt:"标记结算时间",settledByName:"结算标记人"};
 return <><ReturnLink fallback="/settlements" label="返回确定数据"/><h1 className="text-2xl font-semibold">{r.day} · {r.anchorName} · {r.backendName}</h1><p className="text-sm text-slate-500">最近更新 {formatDateTime(r.updatedAt)} · 版本 {r.version}{r.deletedAt?" · 已删除":""}</p><SettlementStatus key={`status-${r.version}`} row={r}/>{!r.deletedAt&&!r.isSettled?<SettlementForm key={r.version} kind="confirmed" initial={{id:r.id,version:r.version}} label="保存更正"><ConfirmedFields row={r} anchors={d.anchors} backends={d.backends} yesterday={dateRange("yesterday")!.to}/></SettlementForm>:<section className="space-y-3 rounded border p-4"><p>{r.deletedAt?"已删除":"已结算，撤销结算后才能修改或删除"}。历史内容和审计保留。</p><dl className="grid gap-3 sm:grid-cols-3">{[["加人数量",r.joinCount],["有效数量",r.effectiveCount],["后端单价（元）",moneyText(BigInt(r.backendUnitCents))],["总价（元）",moneyText(totalCents(r.effectiveCount,r.backendUnitCents))],["主播提成单价（元）",moneyText(BigInt(r.anchorUnitCents))],["主播提成（元）",moneyText(totalCents(r.effectiveCount,r.anchorUnitCents))]].map(([label,value])=><div key={label}><dt className="text-sm text-muted-foreground">{label}</dt><dd>{value}</dd></div>)}</dl></section>}{(!r.isSettled||!!r.deletedAt)&&<details className="rounded border p-4"><summary>{r.deletedAt?"恢复数据":"删除数据"}</summary><SettlementForm key={`recycle-${r.version}`} kind="recycle" initial={{id:r.id,version:r.version,operation:r.deletedAt?"restore":"delete"}} label={r.deletedAt?"确认恢复":"确认移入回收站"}><Reason/></SettlementForm></details>}<details className="rounded border p-4"><summary>修改记录</summary><CorrectionHistory rows={d.history.map(h=>{const v=h.detail as {actorName:string;reason:string;before:Record<string,unknown>|null;after:Record<string,unknown>};return {...h,detail:{actorName:v.actorName,reason:v.reason||"首次录入",changes:Object.entries(labels).filter(([key])=>JSON.stringify(v.before?.[key])!==JSON.stringify(v.after[key])).map(([key,label])=>({field:label,before:String(v.before?.[key]??"未记录"),after:String(v.after[key]??"未记录")}))}};})}/></details></>;
}
