ALTER TABLE "User" ADD COLUMN "nickname" TEXT NOT NULL DEFAULT '', ADD COLUMN "contactPhone" TEXT NOT NULL DEFAULT '', ADD COLUMN "profileVersion" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DouyinAccount" ALTER COLUMN "controllerId" DROP NOT NULL;
ALTER TABLE "AccountRecord" ALTER COLUMN "controllerId" DROP NOT NULL, ALTER COLUMN "controllerName" DROP NOT NULL;
ALTER TABLE "LiveReport" ALTER COLUMN "controllerId" DROP NOT NULL, ALTER COLUMN "controllerName" DROP NOT NULL;
