import Link from "@/components/context-link";
import {confirmedList} from "@/modules/settlements/queries";
import {settlementFilters,moneyText,totalCents} from "@/modules/settlements/schema";
import {SettlementFilters} from "@/components/settlement-filters";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const raw=await searchParams;if(!settlementFilters.safeParse(raw).success)return <p>筛选条件无效，请检查日期。</p>;const d=await confirmedList(raw),f=d.filters;
 const url=(page:number,trash=f.trash)=>`/settlements?${new URLSearchParams({from:f.from,to:f.to,anchorId:f.anchorId,backendId:f.backendId,page:String(page),trash,...(f.preset?{preset:f.preset}:{})})}`;
 return <><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">确定打粉数据{f.trash==="true"?" · 回收站":""}</h1><nav className="flex gap-4 text-sm"><Link href="/settlements/new">录入确定数据</Link><Link href="/settlements/backends">后端资料</Link><Link href={url(1,f.trash==="true"?"false":"true")}>{f.trash==="true"?"正常数据":"回收站"}</Link></nav></header><p className="text-sm text-slate-500">仅登记昨天及以前；保存即展示给主播。总价和主播提成都按有效数量计算，不代表已经收款或发放。</p><SettlementFilters path="/settlements" filters={f} anchors={d.anchors} backends={d.backends}/><p className="rounded border bg-white p-3 text-sm">筛选合计：{d.count}条 · 加人 {d.summary.joins} · 有效 {d.summary.effective} · 总价 ¥{d.summary.revenue} · 主播提成 ¥{d.summary.commission}</p><div className="overflow-x-auto rounded border bg-white"><table className="w-full whitespace-nowrap text-left text-sm"><thead><tr>{["日期","主播","后端名称","后端链接","加人数量","有效数量","后端单价","总价","主播提成单价","主播提成","操作"].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{d.rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.day}</td><td className="p-3">{r.anchorName}</td><td className="p-3">{r.backendName}</td><td className="p-3"><a href={r.backendUrl} target="_blank" rel="noopener noreferrer" className="underline">查看链接</a></td><td className="p-3">{r.joinCount}</td><td className="p-3">{r.effectiveCount}</td><td className="p-3">{moneyText(BigInt(r.backendUnitCents))}</td><td className="p-3">{moneyText(totalCents(r.effectiveCount,r.backendUnitCents))}</td><td className="p-3">{moneyText(BigInt(r.anchorUnitCents))}</td><td className="p-3">{moneyText(totalCents(r.effectiveCount,r.anchorUnitCents))}</td><td className="p-3"><Link href={`/settlements/${r.id}`}>{r.deletedAt?"查看 / 恢复":"查看 / 编辑 / 删除"}</Link></td></tr>)}{!d.rows.length&&<tr><td colSpan={11} className="p-8 text-center">暂无确定数据</td></tr>}</tbody></table></div><nav className="flex justify-between text-sm">{f.page>1?<Link href={url(f.page-1)}>上一页</Link>:<span/>}<span>{f.page} / {d.pages}</span>{f.page<d.pages?<Link href={url(f.page+1)}>下一页</Link>:<span/>}</nav></>;
}
