"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { LogoutButton } from "@/components/logout-button";
const links = [["/workbench/attendance", "上班/下班"], ["/controller", "直播工作"], ["/workbench/history", "场次纪录"], ["/workbench/shifts", "上班纪录"], ["/resources/anchors", "协作主播"], ["/resources/rooms", "负责直播间"], ["/resources/numbers", "负责手机号"], ["/resources/phones", "负责手机"], ["/resources/equipment", "负责设备"], ["/resources/materials", "负责物资"], ["/controller/profile", "个人资料"]];
export function ControllerShell({ name, children }: { name: string; children: React.ReactNode }) {
  const path = usePathname();
  return <div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-white px-6"><Link href="/controller" className="font-semibold">星熠传媒 · 直播中控工作台</Link><nav className="flex items-center gap-4 text-sm"><Link href="/controller">直播工作</Link><span className="text-muted-foreground">{name}</span><LogoutButton /></nav></header><div className="lg:grid lg:grid-cols-[210px_minmax(0,1fr)]"><aside className="border-r bg-white p-4 lg:sticky lg:top-16 lg:h-[calc(100vh-4rem)] lg:overflow-y-auto"><nav aria-label="直播中控菜单" className="flex gap-1 overflow-x-auto lg:block lg:space-y-1">{links.map(([href,label]) => { const active = href === "/controller" ? path === href || path === "/workbench" || path.startsWith("/workbench/accounts/") || path.startsWith("/workbench/sessions/") : path.startsWith(href); return <Link key={href} href={href} aria-current={active ? "page" : undefined} className={`block shrink-0 rounded-lg px-3 py-3 text-sm ${active ? "bg-emerald-900 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{label}</Link>; })}</nav><p className="mt-6 hidden px-3 text-xs leading-5 text-muted-foreground lg:block">专注开播准备、直播执行和下播收尾。人员、账号和物资资料仅供查阅，调整请联系负责人。</p></aside><main className="min-w-0 space-y-6 p-4 lg:p-6">{children}</main></div></div>;
}
