"use client";
import { startTransition, useActionState,useState } from "react";
import { useRouter } from "next/navigation";
import { createDirectAction } from "@/modules/direct-leads/actions";
export function DirectLeadCreate({accounts,anchors}:{accounts:{id:string;name:string;douyinId:string;externalAnchorId:string|null}[];anchors:{id:string;name:string}[]}){
 const router=useRouter(),[accountId,setAccount]=useState(""),[anchorId,setAnchor]=useState("");
 const[state,action,pending]=useActionState(async(previous:{error?:string;id?:string},form:FormData)=>{const result=await createDirectAction(previous,form);if(result.id)router.push(`/leads/direct/${result.id}`);return result;},{});
 return <form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);startTransition(()=>action(data));}} className="max-w-2xl space-y-4"><label className="block">抖音账号<select name="accountId" required value={accountId} onChange={e=>{setAccount(e.target.value);setAnchor(accounts.find(a=>a.id===e.target.value)?.externalAnchorId??"");}} className="mt-1 w-full rounded border p-2"><option value="">请选择外部主播账号</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.douyinId}</option>)}</select></label><label className="block">本场外部主播<select name="externalAnchorId" required value={anchorId} onChange={e=>setAnchor(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">请选择</option>{anchors.map(a=><option key={a.id} value={a.id}>{a.name}（外部）</option>)}</select></label><label className="block">实际开播时间（北京时间）<input type="datetime-local" name="startedAt" required className="mt-1 w-full rounded border p-2"/></label><label className="block">场次名称<input name="label" required maxLength={30} placeholder="例如：晚上场" className="mt-1 w-full rounded border p-2"/></label>{state.error&&<p role="alert" className="text-red-700">{state.error}</p>}<button disabled={pending||!accounts.length} className="rounded bg-emerald-900 px-4 py-2 text-white">{pending?"建档中…":"确认并填写数据"}</button>{!accounts.length&&<p>暂无可用外部主播账号，请联系老板建档。</p>}</form>;
}
