"use client";
import { startTransition, useActionState, useState } from "react";
import { useRouter } from "next/navigation";
import { externalAnchorAction } from "@/modules/external-anchors/actions";
type Account={id:string;version:number;name:string;douyinId:string;active:boolean};
type Anchor={id:string;version:number;name:string;notes:string;active:boolean;accounts:Account[]};
const input="mt-1 w-full rounded border p-2";
export function ExternalAnchorForm({initial,toggle=false}:{initial?:Anchor;toggle?:boolean}) {
 const router=useRouter();const [accounts,setAccounts]=useState<Account[]>(initial?.accounts??[{id:"",version:0,name:"",douyinId:"",active:true}]);
 const [state,action,pending]=useActionState(async(previous:{error?:string;success?:string},form:FormData)=>{const result=await externalAnchorAction(previous,form);if(result.success){if(initial)router.refresh();else window.location.reload();}return result;},{});
 const change=(index:number,patch:Partial<Account>)=>setAccounts(rows=>rows.map((r,i)=>i===index?{...r,...patch}:r));
 return <form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);startTransition(()=>action(data));}} className="space-y-3"><input type="hidden" name="id" value={initial?.id??""}/><input type="hidden" name="version" value={initial?.version??0}/><input type="hidden" name="command" value={toggle?"toggle":"save"}/>{toggle?<p>确认{initial?.active?"停用":"启用"}此外部主播？历史记录保留。</p>:<><label className="block">姓名 / 昵称<input name="name" required maxLength={100} defaultValue={initial?.name} className={input}/></label><input type="hidden" name="accounts" value={JSON.stringify(accounts)}/><fieldset className="space-y-2"><legend>抖音账号</legend>{accounts.map((a,i)=><div key={a.id||`new-${i}`} className="grid gap-2 rounded border p-3 md:grid-cols-[1fr_1fr_auto]"><label>抖音名称<input required maxLength={100} value={a.name} onChange={e=>change(i,{name:e.target.value})} className={input}/></label><label>抖音号<input required maxLength={100} value={a.douyinId} onChange={e=>change(i,{douyinId:e.target.value})} className={input}/></label>{a.id?<button type="button" onClick={()=>change(i,{active:!a.active})}>{a.active?"停用账号":"已停用 · 启用"}</button>:<button type="button" onClick={()=>setAccounts(rows=>rows.filter((_,n)=>n!==i))}>移除此行</button>}</div>)}<button type="button" onClick={()=>setAccounts(rows=>[...rows,{id:"",version:0,name:"",douyinId:"",active:true}])}>＋ 添加抖音账号</button></fieldset><label className="block">备注<textarea name="notes" maxLength={2000} defaultValue={initial?.notes} className={input}/></label></>}{state.error&&<p role="alert" className="text-red-700">{state.error}</p>}{state.success&&<p role="status">{state.success}</p>}<button disabled={pending} className="rounded bg-slate-900 px-4 py-2 text-white">{pending?"保存中…":toggle?"确认":"保存"}</button></form>;
}
