import Link from "./context-link";
import { SessionRecycleForm } from "./session-management-form";
import { getManagedSessions } from "@/modules/workbench/queries";
import type { ManagementParams } from "@/modules/workbench/management";
import { statusLabels, workStatusLabel } from "@/modules/workbench/schema";
import { formatDateTime } from "@/lib/datetime";
import { ManagementFilters, ManagementPager } from "./work-management-filters";
export async function ManagedSessionList({ params }: { params: ManagementParams }) {
  const data = await getManagedSessions(params), trash = params.trash === "yes";
  return <><div className="flex items-center justify-between gap-3"><h1 className="text-2xl font-semibold">{trash ? "场次回收站" : "场次执行记录"}</h1><div className="flex gap-4 text-sm"><Link className="underline" href="/workbench/history/new">补录场次</Link><Link className="underline" href={trash ? "/workbench/history" : "?trash=yes"}>{trash ? "返回场次列表" : "回收站"}</Link></div></div>
    <ManagementFilters params={params} people={data.people} accounts={data.accounts} statuses={statusLabels} />
    <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/50"><tr>{["账号","场次","实际中控","开播 / 下播时间","状态","操作"].map(t => <th key={t} className="whitespace-nowrap p-3">{t}</th>)}</tr></thead><tbody>{data.rows.map(s => <tr key={s.id} className="border-t align-top"><td className="p-3">{s.sourceRecord.name}<p className="text-xs text-muted-foreground">{s.sourceRecord.douyinId}</p></td><td className="p-3">{s.label}{s.supplementedAt && <p className="text-xs text-muted-foreground">老板补录</p>}</td><td className="p-3">{s.actualControllerName ?? s.sourceRecord.controllerName ?? "未记录"}</td><td className="whitespace-nowrap p-3">{s.startedAt ? formatDateTime(s.startedAt, true) : "未开播"}<br />{s.endedAt ? formatDateTime(s.endedAt, true) : "—"}</td><td className="p-3">{workStatusLabel(s)}{trash && <p className="text-xs">删除原因：{s.deleteReason}</p>}</td><td className="space-y-2 p-3"><div className="flex gap-3"><Link className="underline" href={`/workbench/sessions/${s.id}`}>查看</Link>{!trash && <Link className="underline" href={`/workbench/sessions/${s.id}?edit=yes#session-edit`}>编辑</Link>}</div>{(trash || ["COMPLETE","CANCELLED"].includes(s.phase)) ? <>{!trash && (s.leadTask && !s.leadTask.deletedAt && !s.leadTask.releasedAt || s.report && !s.report.deletedAt) ? <div className="text-xs"><p>删除前请先处理关联数据：</p>{s.leadTask && !s.leadTask.deletedAt && !s.leadTask.releasedAt && <Link className="block underline" href={`/leads/${s.leadTask.id}`}>导粉认领及数据</Link>}{s.report && !s.report.deletedAt && <Link className="block underline" href={`/live-reports/${s.report.id}`}>直播 / 打粉报表</Link>}</div> : <SessionRecycleForm id={s.id} version={s.version} deleted={trash} />}</> : <p className="text-xs text-muted-foreground">归档后可删除</p>}</td></tr>)}</tbody></table>{!data.rows.length && <p className="p-6 text-sm">暂无记录</p>}</div><ManagementPager params={params} {...data} /></>;
}
