"use client";
import {startTransition,useActionState,useState} from "react";
import {useRouter,usePathname,useSearchParams} from "next/navigation";
import {settlementAction} from "@/modules/settlements/actions";
import {followHref} from "@/lib/navigation-trail";
import {moneyText,totalCents,unitCents} from "@/modules/settlements/schema";
const input="w-full rounded-lg border bg-white px-3 py-2 text-sm";
export function SettlementForm({kind,initial={},children,label="保存",created=false}:{kind:"backend"|"confirmed"|"recycle";initial?:Record<string,string|number>;children:React.ReactNode;label?:string;created?:boolean}) {
 const router=useRouter(),path=usePathname(),search=useSearchParams();
 const [state,action,pending]=useActionState(async(previous:Awaited<ReturnType<typeof settlementAction>>,form:FormData)=>{const r=await settlementAction(previous,form);if(r.success){if(kind==="confirmed")router.replace(followHref(`/settlements/${r.id}`,path+"?"+search));else if(created)window.location.reload();else router.refresh();}return r;},{});
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);startTransition(()=>action(form));}}><input type="hidden" name="kind" value={kind}/>{Object.entries(initial).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}{children}{state.error&&<p role="alert" className="text-sm text-red-700">{state.error}</p>}{state.success&&<p role="status" className="text-sm text-green-800">{state.success}</p>}<button disabled={pending} className="rounded-lg bg-emerald-900 px-4 py-2 text-white disabled:opacity-50">{pending?"保存中…":label}</button></form>;
}
export function Reason(){return <label className="block text-sm">更正 / 操作原因<textarea name="reason" required maxLength={2000} className={input}/></label>;}
export function BackendFields({row}:{row?:{name:string;url:string;active:boolean}}){return <><div className="grid gap-4 md:grid-cols-3"><label>后端名称<input name="name" defaultValue={row?.name} required maxLength={100} className={input}/></label><label>后端链接<input name="url" type="url" defaultValue={row?.url} required maxLength={2000} className={input}/></label><label>状态<select name="active" defaultValue={String(row?.active??true)} className={input}><option value="true">启用</option><option value="false">停用</option></select></label></div>{row&&<Reason/>}</>;}
export function ConfirmedFields({row,anchors,backends,yesterday}:{row?:{day:string;anchorId:string;backendId:string;joinCount:number;effectiveCount:number;backendUnitCents:number;anchorUnitCents:number};anchors:{id:string;name:string}[];backends:{id:string;name:string;active:boolean}[];yesterday:string}) {
 const [effective,setEffective]=useState(String(row?.effectiveCount??"")),[backend,setBackend]=useState(row?(row.backendUnitCents/100).toFixed(2):""),[anchor,setAnchor]=useState(row?(row.anchorUnitCents/100).toFixed(2):"");
 const calc=(unit:string)=>/^\d+$/.test(effective)&&/^\d{1,7}(\.\d{1,2})?$/.test(unit)?moneyText(totalCents(Number(effective),unitCents(unit))):"—";
 return <><div className="grid gap-4 md:grid-cols-3"><label>日期<input name="day" type="date" max={yesterday} defaultValue={row?.day??yesterday} required className={input}/></label><label>主播<select name="anchorId" defaultValue={row?.anchorId??""} required className={input}><option value="">请选择主播</option>{anchors.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>后端<select name="backendId" defaultValue={row?.backendId??""} required className={input}><option value="">请选择后端</option>{backends.filter(b=>b.active||b.id===row?.backendId).map(b=><option key={b.id} value={b.id}>{b.name}{!b.active?"（已停用）":""}</option>)}</select></label><label>加人数量<input name="joinCount" type="number" min="0" step="1" required defaultValue={row?.joinCount} className={input}/></label><label>有效数量<input name="effectiveCount" type="number" min="0" step="1" required value={effective} onChange={e=>setEffective(e.target.value)} className={input}/></label><label>后端单价（元/个）<input name="backendUnit" required inputMode="decimal" value={backend} onChange={e=>setBackend(e.target.value)} className={input}/></label><p>总价（自动）<output className="block p-2">{calc(backend)} 元</output></p><label>主播提成单价（元/个）<input name="anchorUnit" required inputMode="decimal" value={anchor} onChange={e=>setAnchor(e.target.value)} className={input}/></label><p>主播提成（自动）<output className="block p-2">{calc(anchor)} 元</output></p></div>{row&&<Reason/>}</>;
}
