"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import Link from "@/components/context-link";
import type {ConfirmedLead} from "@/app/generated/prisma/client";
import {settlementAction} from "@/modules/settlements/actions";
import {moneyText,totalCents} from "@/modules/settlements/schema";
import {formatDateTime} from "@/lib/datetime";

type StatusRow=Pick<ConfirmedLead,"id"|"version"|"isSettled"|"settledAt"|"settledByName"|"deletedAt">;
async function saveStatus(operation:string,records:{id:string;version:number}[],reason="") {
  const form=new FormData();form.set("kind","status");form.set("operation",operation);form.set("records",JSON.stringify(records));form.set("reason",reason);
  return settlementAction({},form);
}
export function SettlementStatus({row}:{row:StatusRow}) {
  const router=useRouter(),[pending,start]=useTransition(),[error,setError]=useState(""),[revoking,setRevoking]=useState(false),[reason,setReason]=useState("");
  function save(operation:string){setError("");start(async()=>{try{const result=await saveStatus(operation,[{id:row.id,version:row.version}],reason);if(result.error)setError(result.error);else{setRevoking(false);setReason("");router.refresh();}}catch{setError("保存失败，状态未改变，请稍后重试");}});}
  return <div className="space-y-2"><label className="flex items-center gap-2"><input type="checkbox" aria-label="已结算" checked={row.isSettled===true} disabled={pending||!!row.deletedAt} onChange={e=>e.target.checked?save("settle"):setRevoking(true)}/>已结算</label>{row.isSettled===null?<div className="text-xs text-amber-700">历史待确认 {!row.deletedAt&&<button type="button" className="underline" disabled={pending} onClick={()=>save("confirmUnpaid")}>确认未结算</button>}</div>:row.isSettled===false&&<p className="text-xs text-muted-foreground">未结算</p>}{row.settledAt&&<p className="text-xs text-muted-foreground">标记结算时间：{formatDateTime(row.settledAt)} · {row.settledByName}</p>}{pending&&<p role="status" className="text-xs">保存中…</p>}{revoking&&<div className="space-y-2 rounded border p-2"><label className="block text-sm">撤销结算原因<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} className="block w-full rounded border p-2"/></label><button type="button" disabled={pending||!reason.trim()} className="mr-3 underline disabled:opacity-50" onClick={()=>save("unsettle")}>确认撤销结算</button><button type="button" disabled={pending} onClick={()=>setRevoking(false)}>取消</button></div>}{error&&<p role="alert" className="whitespace-normal text-sm text-red-700">{error}</p>}</div>;
}
export function ConfirmedTable({rows}:{rows:ConfirmedLead[]}) {
 const router=useRouter(),[selected,setSelected]=useState<Record<string,{id:string;version:number;cents:string}>>({}),[pending,start]=useTransition(),[error,setError]=useState("");
 const eligible=rows.filter(r=>!r.deletedAt&&r.isSettled!==true),chosen=Object.values(selected);
 const amount=moneyText(chosen.reduce((n,r)=>n+BigInt(r.cents),BigInt(0)));
 function select(row:ConfirmedLead,checked:boolean){setSelected(prev=>{const next={...prev};if(checked)next[row.id]={id:row.id,version:row.version,cents:totalCents(row.effectiveCount,row.backendUnitCents).toString()};else delete next[row.id];return next;});}
 function batch(){if(!confirm(`确认将所选 ${chosen.length} 条、总金额 ¥${amount} 标记为后端已结清？`))return;setError("");start(async()=>{try{const result=await saveStatus("settle",chosen.map(({id,version})=>({id,version})));if(result.error)setError(result.error);else{setSelected({});router.refresh();}}catch{setError("保存失败，本次未提交结算标记，请刷新核对");}});}
 return <section className="space-y-3">{!!eligible.length&&<div className="flex flex-wrap items-center gap-4 text-sm"><label><input type="checkbox" aria-label="选择当前页可结算记录" disabled={pending} checked={eligible.every(r=>!!selected[r.id])} onChange={e=>setSelected(e.target.checked?Object.fromEntries(eligible.map(r=>[r.id,{id:r.id,version:r.version,cents:totalCents(r.effectiveCount,r.backendUnitCents).toString()}])):{})}/> 选择当前页可结算记录</label><button type="button" disabled={pending||!chosen.length} className="rounded border px-3 py-2 disabled:opacity-50" onClick={batch}>{pending?"保存中…":"批量标记已结算"}</button><span>已选 {chosen.length} 条 · ¥{amount}</span></div>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="overflow-x-auto rounded border bg-white"><table className="w-full whitespace-nowrap text-left text-sm"><thead><tr>{["选择","日期","主播","后端名称","加人数量","有效数量","后端单价","总价","主播提成单价","主播提成","已结算","操作"].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3"><input type="checkbox" aria-label={`选择 ${r.day} ${r.anchorName} ${r.backendName}`} checked={!!selected[r.id]} disabled={pending||!!r.deletedAt||r.isSettled===true} onChange={e=>select(r,e.target.checked)}/></td><td className="p-3">{r.day}</td><td className="p-3">{r.anchorName}</td><td className="p-3">{r.backendName}</td><td className="p-3">{r.joinCount}</td><td className="p-3">{r.effectiveCount}</td><td className="p-3">{moneyText(BigInt(r.backendUnitCents))}</td><td className="p-3">{moneyText(totalCents(r.effectiveCount,r.backendUnitCents))}</td><td className="p-3">{moneyText(BigInt(r.anchorUnitCents))}</td><td className="p-3">{moneyText(totalCents(r.effectiveCount,r.anchorUnitCents))}</td><td className="p-3"><SettlementStatus key={r.version} row={r}/></td><td className="p-3"><Link href={`/settlements/${r.id}`}>{r.deletedAt?"查看 / 恢复":r.isSettled?"查看 / 撤销结算":"查看 / 编辑 / 删除"}</Link></td></tr>)}{!rows.length&&<tr><td colSpan={12} className="p-8 text-center">暂无确定数据</td></tr>}</tbody></table></div></section>;
}
