import { WorkSessionCorrections, CorrectionHistory } from "./work-corrections";
import { formatDateTime } from "@/lib/datetime";
import { WorkEvidenceFields } from "@/components/work-evidence-fields";
import { WorkflowEditor } from "@/components/workflow-editor";
import { isExecutionController } from "@/lib/auth/account-permissions";
import { WorkTimeInput } from "@/components/work-time-input";
import { WorkTaskTable } from "@/components/work-task-table";
import { WorkWrapFields } from "@/components/work-wrap-fields";
import { WorkSessionData } from "@/components/work-session-data";
import { notFound } from "next/navigation";
import { requirePageUser, requirePasswordChanged } from "@/lib/auth/permissions";
import { getWorkSession } from "@/modules/workbench/queries";
import { isInterrupted, isOtherEnd, workflowSchema, phases, phaseLabels, workStatusLabel, type Progress } from "@/modules/workbench/schema";
import { shanghaiInput } from "@/modules/live-reports/schema";
import { WorkActionForm } from "@/components/work-action-form";
import { WorkLiveClock } from "@/components/work-live-clock";
import { WorkStageTabs } from "@/components/work-stage-tabs";
import { WorkScripts } from "@/components/work-scripts";
const inputClass = "w-full rounded-lg border px-3 py-2 text-sm";
const buttonClass = "rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground";
export async function WorkSessionView({ id }: { id: string }) {
  const user = await requirePageUser(); await requirePasswordChanged(user);
  const result = await getWorkSession(id); if (!result) notFound();
  const { session: s, editable, controllers, accountWorkflowVersion, corrections } = result, source = s.sourceRecord;
  const workflow = workflowSchema.parse(s.workflow), progress = s.progress as Progress;
  const open = editable && !["COMPLETE", "CANCELLED"].includes(s.phase);
  const currentPhase = { PREPARING: "before", LIVE: "live", WRAP: "after", COMPLETE: "after", CANCELLED: "before" }[s.phase];

  const evidenceCount = s.screenshots.filter(f => ["end", "violation"].includes(f.event.kind)).length;
  const initialNote = [s.wrapNote || (isInterrupted(s.outcome) ? s.events.find(e => e.kind === "end")?.body : ""), s.hasViolation ? s.violationDetail : ""].filter(Boolean).join("\n");
  const remaining = workflow.after.filter((_, i) => !progress[`after:${i}`] || progress[`after:${i}`].status !== "done");
  const base = { id, version: s.version };
  return <><header className="space-y-2"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold">{source.name} · {s.label}</h1><span className="rounded-full bg-muted px-3 py-1 text-sm">{workStatusLabel(s)}</span></div><p className="text-sm text-muted-foreground">{source.branchName} · 主播 {source.anchorName ?? "无"} · 运营 {source.operatorName ?? "无"} · 本场直播中控 {s.actualControllerName ?? source.controllerName}</p><p className="text-sm text-muted-foreground">实际开播：{s.startedAt ? formatDateTime(s.startedAt, true) : "未开播"} · 实际下播：{s.endedAt ? formatDateTime(s.endedAt, true) : "未记录"}</p><p className="text-xs text-muted-foreground">登录账号：{s.loginUserName ?? source.controllerName}{!s.shiftId ? " · 历史场次（无上班关联）" : ""}</p><p className="text-xs text-muted-foreground">本场流程创建于第 {s.workflowVersion} 版，话术可单独同步 · 勾选或提交后保存到服务器；完成时间自动记录</p></header>
    {s.phase === "LIVE" && s.startedAt && <WorkLiveClock startedAt={s.startedAt.toISOString()} sessionId={id} tasks={workflow.live.map((task, index) => ({ ...task, index, status: progress[`live:${index}`]?.status ?? "pending" }))} />}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-5">

    <WorkStageTabs key={s.phase} initial={currentPhase} items={phases.map(phase => ({ id: phase, label: phaseLabels[phase], content: <div className="space-y-4">
      {phase === "before" && <>{open && s.phase === "PREPARING" && <section className="space-y-3 rounded-xl border p-4"><p className="text-sm">本场直播中控：{s.actualControllerName ?? source.controllerName}（已确认）</p><details key={s.actualControllerId}><summary className="cursor-pointer text-sm underline">修改</summary><WorkActionForm fields={{ ...base, command: "controller" }}><label className="text-sm">本场直播中控<select name="actualControllerId" defaultValue={s.actualControllerId ?? s.controllerId} className={inputClass}>{!controllers.some(p => p.id === (s.actualControllerId ?? s.controllerId)) && <option value={s.actualControllerId ?? s.controllerId}>{s.actualControllerName ?? source.controllerName}</option>}{controllers.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="text-xs text-muted-foreground">开播后锁定实际直播中控。选择人员不会赋予其账号访问权限。</p><button className={buttonClass}>确认</button></WorkActionForm></details></section>}</>}
      <WorkTaskTable {...base} phase={phase} tasks={workflow[phase]} progress={progress} editable={open && phase === currentPhase} startedAt={s.startedAt?.toISOString() ?? null} />
      {open && ((phase === "before" && s.phase === "PREPARING") || (phase === "live" && s.phase === "LIVE")) && <section className="space-y-3 rounded-xl border p-5"><h2 className="font-semibold">{s.phase === "PREPARING" ? "确认已实际开播" : "确认已实际下播"}</h2><p className="text-xs text-muted-foreground">此操作只记录系统状态，不控制抖音开关播。时间按北京时间填写。</p><WorkActionForm key={s.phase} fields={{ ...base, command: s.phase === "PREPARING" ? "start" : "end" }}><WorkTimeInput initial={shanghaiInput(new Date())} label={`实际${s.phase === "PREPARING" ? "开播" : "下播"}时间`} />{s.phase === "PREPARING" ? <><label className="text-sm">补填原因（开播时间早于系统准备记录时必填）<textarea name="reason" maxLength={2000} className={inputClass} /></label></> : <WorkEvidenceFields mode="end" />}<button className={buttonClass}>{s.phase === "PREPARING" ? "确认开播" : "确认下播，进入收尾"}</button></WorkActionForm></section>}
      {phase === "before" && <>{open && s.phase === "PREPARING" && <section className="space-y-3 rounded-xl border p-5"><h2 className="font-semibold">未正常开播</h2><p className="text-xs text-muted-foreground">验证失败、账号封禁等导致本场无法开播时，填写原因和截图，保留本次准备记录。</p><WorkActionForm fields={{ ...base, command: "unstarted" }}><WorkEvidenceFields mode="unstarted" /><button className={buttonClass}>保存未正常开播记录</button></WorkActionForm></section>} {open && s.phase === "PREPARING" && <details className="rounded-xl border p-5"><summary className="cursor-pointer text-sm text-muted-foreground">本场不开播，取消准备</summary><WorkActionForm className="mt-3 space-y-3" fields={{ ...base, command: "cancel" }}><input name="note" required maxLength={2000} placeholder="取消原因" aria-label="取消原因" className={inputClass} /><button className="rounded-lg border px-4 py-2 text-sm">取消本场准备</button></WorkActionForm></details>}</>}
      {phase === "after" && ["WRAP", "COMPLETE"].includes(s.phase) && <section className="space-y-4 rounded-xl border p-4"><h2 className="font-semibold">本场收尾</h2>{s.phase === "COMPLETE" && <><p className="text-sm">{s.hasIncident === null ? "历史未记录异常确认" : s.hasIncident ? `本场有异常${s.hasViolation ? " · 违规" : ""}${s.hasOtherIncident ? " · 其他异常" : ""}` : "本场无异常"}</p><p className="whitespace-pre-wrap text-sm">{s.wrapNote}</p>{s.violationDetail && s.violationDetail !== s.wrapNote && <p className="whitespace-pre-wrap text-sm">历史违规说明：{s.violationDetail}</p>}</>}{!isExecutionController(user) && <WorkSessionData id={id} />}{open && s.phase === "WRAP" && <><p className="text-sm">{remaining.length ? `请完成下播后检查：${remaining.map(t => t.title).join("、")}` : "下播后检查已完成"}</p><WorkActionForm fields={{ ...base, command: "complete" }}><WorkWrapFields interrupted={isOtherEnd(s.outcome)} hasViolation={s.hasViolation} hasOtherIncident={s.hasOtherIncident} note={initialNote} evidenceCount={evidenceCount} /><button disabled={remaining.length > 0} className={`${buttonClass} disabled:opacity-50`}>确认完成本场收尾</button></WorkActionForm></>}</section>}
    </div> }))} />
    {editable && ["COMPLETE", "CANCELLED"].includes(s.phase) && <WorkSessionCorrections session={s} controllers={controllers} workflow={workflow} progress={progress} />}
    {corrections.length > 0 && <details className="space-y-4 rounded-xl border p-5"><summary className="cursor-pointer font-semibold">本场更正历史 · {corrections.length} 次</summary><CorrectionHistory rows={corrections} /></details>}
    </div><div className="min-w-0 space-y-5 xl:sticky xl:top-20"><WorkScripts workflow={workflow} />{s.screenshots.length > 0 && <details className="rounded-xl border p-5"><summary className="cursor-pointer font-semibold">本场全部截图 · {s.screenshots.length} 张</summary><ol className="mt-3 max-h-80 space-y-3 overflow-y-auto">{s.screenshots.map((file, i) => <li key={file.id} className="text-sm"><a href={`/workbench/screenshots/${file.id}`} target="_blank" rel="noreferrer" className="underline">查看截图 {i + 1}</a><p className="whitespace-pre-wrap break-words text-xs text-muted-foreground">{file.event.body}</p></li>)}</ol></details>}{open && accountWorkflowVersion > 0 && <details className="rounded-xl border p-5"><summary className="cursor-pointer font-semibold">编辑本场及账号话术</summary><WorkflowEditor accountId={s.accountId} version={accountWorkflowVersion} initial={workflow} scriptsOnly sessionId={id} sessionVersion={s.version} /></details>}<section className="rounded-xl border p-5"><h2 className="mb-4 font-semibold">本场执行记录</h2><p className="mb-3 text-xs text-muted-foreground">最近 200 条，全部操作保留在服务器。</p><ol className="max-h-[600px] space-y-4 overflow-y-auto">{s.events.map(e => <li key={e.id} className="border-b pb-3 text-sm"><p className="whitespace-pre-wrap break-words">{e.body || ({ complete: "完成收尾", create: "开始准备" } as Record<string, string>)[e.kind]}</p><div className="mt-2 flex flex-wrap gap-2">{e.screenshots.map((file, i) => <a key={file.id} href={`/workbench/screenshots/${file.id}`} target="_blank" rel="noreferrer" className="rounded border px-2 py-1 text-xs underline">查看截图 {i + 1}</a>)}</div><p className="mt-1 text-xs text-muted-foreground">{e.actorName} · {e.createdAt.toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })}</p></li>)}</ol></section></div></div>
  </>;
}
