import { accountStatusLabel } from "@/lib/account-status";
import Link from "next/link";


import { getWorkbench } from "@/modules/workbench/queries";
import { moneyPending, workStatusLabel } from "@/modules/workbench/schema";
export async function WorkbenchHome({ name }: { name: string }) {
  const { accounts, sessions, executionOnly } = await getWorkbench();
  const active = sessions.filter(s => s.phase === "LIVE" || s.phase === "PREPARING");
  const pending = sessions.filter(s => s.phase !== "LIVE" && s.phase !== "PREPARING");
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b pb-5"><div className="space-y-2"><p className="text-sm text-muted-foreground">你好，{name}</p><h1 className="text-3xl font-semibold">直播中控工作台</h1><p className="text-sm text-muted-foreground">选账号、做准备、跟进直播、完成收尾。</p></div>{!executionOnly && <nav className="flex flex-wrap gap-3 text-sm"><Link href="/live-reports/new" className="rounded-lg bg-emerald-900 px-4 py-3 text-white">填写本场数据</Link><Link href="/live-reports" className="rounded-lg border px-4 py-3">维护我的数据</Link></nav>}</header>
    <Link href="/workbench/attendance" className="inline-block text-sm text-emerald-800 underline">上班登记与设备检查 →</Link>
    <div className="grid grid-cols-3 gap-3">{[["负责账号", accounts.length], ["进行中的场次", active.length], [executionOnly ? "待收尾场次" : "待收尾 / 补数据", pending.length]].map(([label, count]) => <section key={label} className="rounded-xl border bg-muted/20 px-4 py-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{count}</p></section>)}</div>
    {active.length > 0 && <section className="space-y-3"><h2 className="text-lg font-semibold">继续本场工作</h2>{active.map(s => <Link key={s.id} href={`/workbench/sessions/${s.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-950"><span className="min-w-0"><strong className="break-words">{s.sourceRecord.name}</strong><span className="ml-3 text-sm">{s.label} · {workStatusLabel(s)}</span></span><span className="shrink-0 rounded-lg bg-emerald-900 px-4 py-2 text-sm text-white">进入本场 →</span></Link>)}</section>}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="min-w-0 space-y-6"><section className="space-y-3"><h2 className="text-lg font-semibold">选择直播账号</h2>{!accounts.length ? <p className="rounded-xl border border-dashed p-8 text-sm text-muted-foreground">还没有分配账号，请联系老板或分公司负责人。</p> : <div className={`grid gap-3 ${accounts.length > 1 ? "md:grid-cols-2" : ""}`}>{accounts.map(a => <Link key={a.id} href={`/workbench/accounts/${a.id}`} className="min-w-0 space-y-3 rounded-xl border p-5 transition-colors hover:border-foreground/30 hover:bg-muted/30"><div className="flex items-start justify-between gap-3"><h3 className="min-w-0 break-words font-semibold">{a.name}</h3><span className="shrink-0 rounded bg-muted px-2 py-1 text-xs text-muted-foreground">{a.banned ? "封禁" : a.active ? a.anchor ? "已分配主播" : "未绑定主播" : "已停用"}</span></div><p className="break-all text-xs text-muted-foreground">抖音号 {a.douyinId} · {a.branch.name}</p><p className="text-sm">主播：{a.anchor?.name ?? "无"}　直播中控：{a.controller?.name ?? "无"}</p>{a.banned && <p className="text-sm text-amber-800">{accountStatusLabel(a)}</p>}{a.purpose && <p className="break-words text-sm text-muted-foreground">{a.purpose}</p>}<p className="border-t pt-3 text-sm font-medium">进入账号工作空间 →</p></Link>)}</div>}</section>
      <section className="space-y-3"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{executionOnly ? "待收尾场次" : "待收尾与待补数据"}</h2><Link href="/workbench/history" className="text-sm text-muted-foreground">全部场次 →</Link></div>{pending.length ? <div className="divide-y rounded-xl border">{pending.map(s => <Link key={s.id} href={`/workbench/sessions/${s.id}`} className="flex flex-wrap items-center justify-between gap-3 p-4 hover:bg-muted/30"><div className="min-w-0"><p className="break-words text-sm font-medium">{s.sourceRecord.name} · {s.label}</p><p className="mt-1 text-xs text-muted-foreground">{s.createdAt.toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })}</p></div><span className="text-xs text-amber-800">{s.phase === "WRAP" ? "待收尾 · " : ""}{executionOnly ? "完成下播检查与违规记录" : !s.report ? "待填直播数据" : s.report.deletedAt ? "直播数据已删除" : s.report.monetizationDeletedAt ? "打粉数据已删除" : moneyPending(s.report, s.leadEligible) ? "待补打粉数据" : "数据已填写"} →</span></Link>)}</div> : <p className="rounded-xl border p-6 text-sm text-muted-foreground">暂无待补事项</p>}<p className="text-xs text-muted-foreground">{executionOnly ? "完成收尾即完成本场工作，历史任务可在场次记录中查看。" : "补数据不影响下一场开播，展示最近 50 条待办。"}</p></section></div>
      <aside className="min-w-0 space-y-4"><section className="space-y-3 rounded-xl border p-5"><h2 className="font-semibold">本人相关资料</h2><div className="grid grid-cols-2 gap-2 text-sm">{[["anchors", "主播"], ["rooms", "直播间"], ["numbers", "手机号"], ["phones", "手机"], ["equipment", "电脑与设备"], ["materials", "物资"]].map(([kind, label]) => <Link key={kind} href={`/resources/${kind}`} className="rounded-lg bg-muted/50 px-3 py-3 hover:bg-muted">{label} →</Link>)}</div></section>
</aside>
    </div>
  </div>;
}
