import Link from "./context-link";
import type { ManagementParams } from "@/modules/workbench/management";
const input = "rounded-lg border px-3 py-2 text-sm";
export function ManagementFilters({ params: p, people, accounts, statuses }: { params: ManagementParams; people: { id: string; name: string }[]; accounts?: { id: string; name: string; douyinId: string }[]; statuses: Record<string,string> }) {
  return <form className="flex flex-wrap items-end gap-3 rounded-xl border p-3">{p.trash === "yes" && <input name="trash" type="hidden" value="yes" />}{accounts && <label className="text-xs">账号<select name="accountId" defaultValue={p.accountId ?? ""} className={`${input} block max-w-56`}><option value="">全部账号</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} · {a.douyinId}</option>)}</select></label>}<label className="text-xs">{accounts ? "中控" : "员工"}<select name="userId" defaultValue={p.userId ?? ""} className={`${input} block`}><option value="">全部员工</option>{people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs">开始日期<input type="date" name="from" defaultValue={p.from} className={`${input} block`} /></label><label className="text-xs">结束日期<input type="date" name="to" defaultValue={p.to} className={`${input} block`} /></label><label className="text-xs">状态<select name="status" defaultValue={p.status ?? ""} className={`${input} block`}><option value="">全部状态</option>{Object.entries(statuses).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-xs">每页<select name="pageSize" defaultValue={["10","20","50"].includes(p.pageSize ?? "") ? p.pageSize : "20"} className={`${input} block`}>{[10,20,50].map(n => <option key={n} value={n}>{n}条</option>)}</select></label><button className={input}>筛选</button><Link className="p-2 text-sm underline" href={p.trash === "yes" ? "?trash=yes" : "?"}>重置</Link></form>;
}
export function ManagementPager({ params, page, pageSize, count }: { params: ManagementParams; page: number; pageSize: number; count: number }) {
  const href = (page: number) => "?" + new URLSearchParams({ ...Object.fromEntries(Object.entries(params).filter(([,v]) => typeof v === "string")) as Record<string,string>, page: String(page), pageSize: String(pageSize) });
  return <nav className="flex gap-4 text-sm">{page > 1 && <Link href={href(page - 1)}>上一页</Link>}<span>共 {count} 条 · 第 {page} 页</span>{page * pageSize < count && <Link href={href(page + 1)}>下一页</Link>}</nav>;
}
