import Link from "next/link";


import { getWorkbench } from "@/modules/workbench/queries";
import { moneyPending, workStatusLabel } from "@/modules/workbench/schema";
export async function WorkbenchHome() {
  const { accounts, sessions, executionOnly } = await getWorkbench();
  const active = sessions.filter(s => s.phase === "LIVE" || s.phase === "PREPARING");
  const pending = sessions.filter(s => s.phase !== "LIVE" && s.phase !== "PREPARING");
  return <div className={`space-y-4 ${executionOnly && pending.length ? "pb-52" : ""}`}>
    <header className="flex flex-wrap items-end justify-between gap-3 border-b pb-3"><div className="space-y-2"><h1 className="text-2xl font-semibold">直播工作</h1><p className="text-sm text-muted-foreground">选账号、做准备、跟进直播、完成收尾。</p></div>{!executionOnly && <nav className="flex flex-wrap gap-3 text-sm"><Link href="/live-reports/new" className="rounded-lg bg-emerald-900 px-4 py-3 text-white">填写本场数据</Link><Link href="/live-reports" className="rounded-lg border px-4 py-3">维护我的数据</Link></nav>}</header>
    <div className="flex flex-wrap gap-x-6 gap-y-2">{[["负责账号", accounts.length], ["进行中的场次", active.length], [executionOnly ? "待收尾场次" : "待收尾 / 补数据", pending.length]].map(([label, count]) => <section key={label} className="flex items-center gap-2"><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm font-semibold tabular-nums">{count}</p></section>)}</div>
    {active.length > 0 && <section className="space-y-3"><h2 className="text-lg font-semibold">继续本场工作</h2>{active.map(s => <Link key={s.id} href={`/workbench/sessions/${s.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-950"><span className="min-w-0"><strong className="break-words">{s.sourceRecord.name}</strong><span className="ml-3 text-sm">{s.label} · {workStatusLabel(s)}</span></span><span className="shrink-0 rounded-lg bg-emerald-900 px-4 py-2 text-sm text-white">进入本场 →</span></Link>)}</section>}
    <section className="space-y-3" aria-label="选择直播账号"><h2 className="text-base font-semibold">选择直播账号</h2>{!accounts.length ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">还没有分配账号，请联系老板或分公司负责人。</p> : <div tabIndex={0} aria-label="直播账号列表" className="grid max-h-[40dvh] lg:max-h-[max(10rem,calc(100dvh-27rem))] grid-cols-1 gap-3 overflow-y-auto overscroll-contain p-1 sm:grid-cols-2 lg:grid-cols-3">{accounts.map(a => <Link key={a.id} href={`/workbench/accounts/${a.id}`} className="min-w-0 space-y-2 rounded-xl border bg-white p-3 transition-colors hover:border-foreground/30 hover:bg-muted/30"><h3 className="break-words font-semibold">{a.name}</h3><p className="break-all text-xs text-muted-foreground">抖音号：{a.douyinId}</p><p className="break-words text-sm">主播：{a.anchor?.name ?? "无"}</p><p className="border-t pt-2 text-sm font-medium">进入账号工作空间 →</p></Link>)}</div>}</section>
      <section aria-label="待收尾场次" className={executionOnly && pending.length ? "fixed inset-x-4 bottom-3 z-20 space-y-2 rounded-xl border border-amber-200 bg-white p-3 shadow-lg lg:left-[226px] lg:right-6" : "space-y-2"}><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{executionOnly ? "待收尾场次" : "待收尾与待补数据"}</h2><Link href="/workbench/history" className="text-sm text-muted-foreground">全部场次 →</Link></div>{pending.length ? <div tabIndex={0} aria-label="待收尾列表" className="max-h-28 divide-y overflow-y-auto overscroll-contain rounded-lg border">{pending.map(s => <Link key={s.id} href={`/workbench/sessions/${s.id}`} className="flex flex-wrap items-center justify-between gap-3 p-2 hover:bg-muted/30"><div className="min-w-0"><p className="break-words text-sm font-medium">{s.sourceRecord.name} · {s.label}</p><p className="mt-1 text-xs text-muted-foreground">{s.createdAt.toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })}</p></div><span className="text-xs text-amber-800">{s.phase === "WRAP" ? "待收尾 · " : ""}{executionOnly ? "完成下播检查与违规记录" : !s.report ? "待填直播数据" : s.report.deletedAt ? "直播数据已删除" : s.report.monetizationDeletedAt ? "打粉数据已删除" : moneyPending(s.report) ? "待补打粉数据" : "数据已填写"} →</span></Link>)}</div> : <p className="rounded-xl border p-3 text-sm text-muted-foreground">暂无待收尾事项</p>}<p className="text-xs text-muted-foreground">{executionOnly ? "完成收尾即完成本场工作，历史任务可在场次记录中查看。" : "补数据不影响下一场开播，展示最近 50 条待办。"}</p></section>
  </div>;
}
