"use client";
import { startTransition, useActionState, useRef, useState } from "react";
import { saveSessionScriptsAction, saveWorkflowAction } from "@/modules/workbench/actions";
import { categories, phaseLabels, phases, moveTask, type Workflow } from "@/modules/workbench/schema";
const inputClass = "w-full rounded-lg border bg-background px-3 py-2 text-sm";
export function WorkflowEditor({ accountId, version, initial, scriptsOnly = false, sessionId, sessionVersion }: { accountId: string; version: number; initial: Workflow; scriptsOnly?: boolean; sessionId?: string; sessionVersion?: number }) {
  const [value, setValue] = useState(initial);
  const [initialVersion] = useState(version);
  const [dragging, setDragging] = useState<{ phase: typeof phases[number]; index: number } | null>(null);
  const dragSource = useRef<typeof dragging>(null);
  const sessionScripts = scriptsOnly && sessionId !== undefined && sessionVersion !== undefined;
  const [state, action, pending] = useActionState(sessionScripts ? saveSessionScriptsAction : saveWorkflowAction, undefined);
  function clearDrag() { dragSource.current = null; setDragging(null); }
  function reorder(phase: typeof phases[number], from: number, to: number) { setValue(current => ({ ...current, [phase]: moveTask(current[phase], from, to) })); clearDrag(); }
  return <form className="space-y-6" onSubmit={event => { event.preventDefault(); const data = new FormData(); data.set("accountId", accountId); data.set("version", String(state?.savedVersion ?? initialVersion)); data.set("mode", scriptsOnly ? "scripts" : "workflow"); if (sessionScripts) { data.set("sessionId", sessionId); data.set("sessionVersion", String(sessionVersion)); } data.set("content", JSON.stringify(scriptsOnly ? value.scripts : value)); startTransition(() => action(data)); }}>
    <p className="text-sm text-muted-foreground">{sessionScripts ? "修改将同步到本场和账号下次开播的话术，其他历史场次保持原样。" : "每个账号独立维护。修改只影响新场次，已开始的场次保留原版本。初始清单供调整，不含示例话术。"}</p>
    {!scriptsOnly && <p className="text-sm text-muted-foreground">拖动事项左上角的“拖动排序”可调整同一阶段顺序，也可使用上移、下移按钮。排序与时间修改后，请点击底部保存。提醒时间可精确到秒。</p>}
    {!scriptsOnly && phases.map(phase => <section key={phase} className="space-y-3"><h3 className="font-semibold">{phaseLabels[phase]}</h3>
      {value[phase].map((task, i) => <div key={i} className={`space-y-2 rounded-lg border p-3 ${dragging?.phase === phase && dragging.index === i ? "border-primary bg-muted/50" : ""}`} data-workflow-phase={phase} data-workflow-index={i}>
        <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><button type="button" disabled={pending} aria-label={`${phaseLabels[phase]}第 ${i + 1} 项拖动排序`} className="touch-none select-none cursor-grab rounded border px-2 py-1 active:cursor-grabbing" onPointerDown={event => { if (event.button !== 0) return; event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); dragSource.current = { phase, index: i }; setDragging(dragSource.current); }} onPointerUp={event => { const target = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-workflow-phase]"); if (!pending && dragSource.current?.phase === phase && target?.dataset.workflowPhase === phase && event.currentTarget.closest("form")?.contains(target)) reorder(phase, dragSource.current.index, Number(target.dataset.workflowIndex)); else clearDrag(); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); }} onPointerCancel={clearDrag}>⠿ 拖动排序</button><span>第 {i + 1} 项</span><button type="button" disabled={pending || i === 0} aria-label={`${phaseLabels[phase]}第 ${i + 1} 项上移`} onClick={() => reorder(phase, i, i - 1)}>上移</button><button type="button" disabled={pending || i === value[phase].length - 1} aria-label={`${phaseLabels[phase]}第 ${i + 1} 项下移`} onClick={() => reorder(phase, i, i + 1)}>下移</button></div>
        <div className="flex gap-2"><input aria-label={`${phaseLabels[phase]}第 ${i + 1} 项名称`} required maxLength={100} value={task.title} className={inputClass} onChange={e => setValue({ ...value, [phase]: value[phase].map((t, n) => n === i ? { ...t, title: e.target.value } : t) })} /><button type="button" className="shrink-0 text-sm text-muted-foreground" onClick={() => setValue({ ...value, [phase]: value[phase].filter((_, n) => n !== i) })}>删除</button></div>
        <textarea aria-label="执行说明" placeholder="执行说明、注意事项或关联的话术标题" maxLength={2000} value={task.detail} className={inputClass} onChange={e => setValue({ ...value, [phase]: value[phase].map((t, n) => n === i ? { ...t, detail: e.target.value } : t) })} />
        {phase === "live" && <div className="space-y-2"><label className="block text-sm">执行方式<select aria-label={`开播中第 ${i + 1} 项执行方式`} className={inputClass} value={task.trigger ?? "timed"} onChange={e => setValue({ ...value, live: value.live.map((t, n) => n === i ? { ...t, trigger: e.target.value as "timed" | "manual" } : t) })}><option value="timed">按开播时间提醒</option><option value="manual">按主播口令 / 随时执行</option></select></label>{task.trigger !== "manual" && <div className="flex flex-wrap items-center gap-2 text-sm"><span>开播后</span><label className="flex items-center gap-2"><input aria-label={`开播中第 ${i + 1} 项分钟`} type="number" min={0} max={1440} step={1} required className="w-20 rounded border px-2 py-1" value={task.minute} onChange={e => setValue({ ...value, live: value.live.map((t, n) => n === i ? { ...t, minute: Number(e.target.value) } : t) })} />分</label><label className="flex items-center gap-2"><input aria-label={`开播中第 ${i + 1} 项秒数`} type="number" min={0} max={59} step={1} required className="w-20 rounded border px-2 py-1" value={task.second ?? 0} onChange={e => setValue({ ...value, live: value.live.map((t, n) => n === i ? { ...t, second: Number(e.target.value) } : t) })} />秒提醒</label></div>}</div>}
      </div>)}
      <button type="button" disabled={value[phase].length >= 40} className="text-sm text-primary" onClick={() => setValue({ ...value, [phase]: [...value[phase], { title: "", detail: "", minute: 0, second: 0 }] })}>＋ 添加事项</button>
    </section>)}
    <section className="space-y-3"><h3 className="font-semibold">本账号话术</h3>
      {value.scripts.map((script, i) => <div key={i} className="space-y-2 rounded-lg border p-3">
        <div className="flex gap-2"><select aria-label="话术分类" className={inputClass} value={script.category} onChange={e => setValue({ ...value, scripts: value.scripts.map((s, n) => n === i ? { ...s, category: e.target.value as typeof script.category } : s) })}>{categories.map(c => <option key={c}>{c}</option>)}</select><button type="button" className="shrink-0 text-sm text-muted-foreground" onClick={() => setValue({ ...value, scripts: value.scripts.filter((_, n) => n !== i) })}>删除</button></div>
        {([['title', '话术标题', 100], ['scene', '适用场景（可选）', 300], ['body', '话术正文', 5000]] as const).map(([key, label, max]) => <textarea key={key} aria-label={label} placeholder={label} required={key !== 'scene'} rows={key === 'body' ? 4 : 1} maxLength={max} value={script[key]} className={inputClass} onChange={e => setValue({ ...value, scripts: value.scripts.map((s, n) => n === i ? { ...s, [key]: e.target.value } : s) })} />)}
      </div>)}
      <button type="button" disabled={value.scripts.length >= 60} className="text-sm text-primary" onClick={() => setValue({ ...value, scripts: [...value.scripts, { category: "关注话术", title: "", body: "", scene: "" }] })}>＋ 添加话术</button>
    </section>
    {state?.error && <p role="alert" className="text-sm text-destructive">{state.error}</p>}{state?.success && <p role="status" className="text-sm text-emerald-700">{state.success}</p>}
    <button disabled={pending} className="rounded-lg bg-primary px-5 py-3 text-sm text-primary-foreground">{pending ? "保存中…" : scriptsOnly ? "保存话术" : "保存流程与话术"}</button>
  </form>;
}
