import Link from "@/components/context-link";
import {comparison} from "@/modules/settlements/queries";
import {settlementFilters} from "@/modules/settlements/schema";
import {SettlementFilters} from "@/components/settlement-filters";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const raw=await searchParams;if(!settlementFilters.safeParse(raw).success)return <p>筛选日期无效</p>;const d=await comparison(raw);
 const url=(page:number)=>`/settlements/comparison?${new URLSearchParams({from:d.filters.from,to:d.filters.to,anchorId:d.filters.anchorId,...(d.filters.preset?{preset:d.filters.preset}:{}),page:String(page)})}`;
 return <><h1 className="text-2xl font-semibold">每日数据对比</h1><p className="text-sm text-slate-500">按北京时间开播日期和主播汇总。差值＝确定数据－已完成场次数据，不自动修改任何数据。</p><SettlementFilters path="/settlements/comparison" filters={d.filters} anchors={d.anchors}/><div className="overflow-x-auto rounded border bg-white"><table className="w-full whitespace-nowrap text-left text-sm"><thead><tr>{["日期","主播","场次加人","确定加人","加人差值","场次有效","确定有效","有效差值","状态"].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{d.rows.map(r=>{const comparable=r.reportCount>0&&r.confirmedCount>0,j=r.confirmedJoins-r.reportJoins,e=r.confirmedEffective-r.reportEffective;return <tr key={r.day+":"+r.anchorId} className={`border-t ${comparable&&(j||e)?"bg-amber-50":""}`}><td className="p-3">{r.day}</td><td className="p-3">{r.anchorName}</td><td className="p-3">{r.reportCount?r.reportJoins:"—"}</td><td className="p-3">{r.confirmedCount?r.confirmedJoins:"—"}</td><td className="p-3 font-medium">{comparable?j:"—"}</td><td className="p-3">{r.reportCount?r.reportEffective:"—"}</td><td className="p-3">{r.confirmedCount?r.confirmedEffective:"—"}</td><td className="p-3 font-medium">{comparable?e:"—"}</td><td className="p-3">{!r.confirmedCount?"未录确定数据":!r.reportCount?"无场次数据":j||e?"有差异":"一致"}{r.pending>0?` · ${r.pending}场数据不完整`:""}</td></tr>;})}{!d.rows.length&&<tr><td colSpan={9} className="p-8 text-center">暂无数据</td></tr>}</tbody></table></div><nav className="flex justify-between text-sm">{d.filters.page>1?<Link href={url(d.filters.page-1)}>上一页</Link>:<span/>}<span>{d.count}条 · {d.filters.page}/{d.pages}</span>{d.filters.page<d.pages?<Link href={url(d.filters.page+1)}>下一页</Link>:<span/>}</nav></>;
}
