import assert from "node:assert/strict";
import {validateTestEnv,resolveTestClient,assertTestDatabase,newRunId,cleanupRun} from "./lib/test-db";
import {saveAccount} from "../modules/accounts/service";
import {saveExternalAnchor} from "../modules/external-anchors/service";
import {createDirectTask,readDirectTask,runDirectCommand,assertNoDirectDuplicate} from "../modules/direct-leads/service";
import {readLeadList,runLeadCommand} from "../modules/leads/service";
import {readLiveReports} from "../modules/live-reports/data";
import {readResourceList} from "../modules/resources/data";
import {readAnchorIncome,saveBackend,saveConfirmed} from "../modules/settlements/service";
import {readComparison} from "../modules/settlements/comparison";
import {leadValues} from "../modules/leads/schema";
import {activeLeadFields} from "../modules/leads/schema";
import {shanghaiInput} from "../modules/live-reports/schema";
import {previewReadToken,requireReadAccountActor} from "../lib/auth/read-actor";
import {submitWorkCommand} from "../modules/workbench/screenshots";
import {runShiftCommand} from "../modules/workbench/shifts";
async function main(){
 const {dbName}=validateTestEnv(),db=resolveTestClient(),marker=newRunId();let verified=false;
 try{
  await assertTestDatabase(db,dbName);verified=true;
  const b=await db.branch.create({data:{name:marker+"-a"}}),other=await db.branch.create({data:{name:marker+"-b"}});
  async function user(label:string,role:"BOSS"|"LEAD_SPECIALIST"|"CONTROLLER"|"ANCHOR"|"OPERATOR",branchId:string|null){const u=await db.user.create({data:{username:marker+label,name:label==="anchor"?"同名主播":label,role,branchId,passwordHash:"not-a-real-hash",mustChangePassword:false}});const token=marker+label;await db.session.create({data:{id:token,userId:u.id,expiresAt:new Date(Date.now()+3600000)}});return {...u,token};}
  const boss=await user("boss","BOSS",null),lead=await user("lead","LEAD_SPECIALIST",b.id),second=await user("second","LEAD_SPECIALIST",b.id),outsider=await user("outsider","LEAD_SPECIALIST",other.id),controller=await user("controller","CONTROLLER",b.id),anchor=await user("anchor","ANCHOR",b.id),operator=await user("operator","OPERATOR",b.id);
  const ext=await db.$transaction(tx=>saveExternalAnchor(tx,boss.token,{name:"同名主播",branchId:b.id,active:"true",version:0},"test"));
  await assert.rejects(db.$transaction(tx=>saveExternalAnchor(tx,lead.token,{name:"禁止",branchId:b.id,active:"true",version:0},"test")),/无权/);
  const input={id:"",version:0,douyinId:marker,name:"外部账号",homepageUrl:"",realName:"",phone:"",purpose:"",notes:"",branchId:b.id,operatorId:operator.id,controllerId:"",anchorId:"",externalAnchorId:ext,active:"true" as const};
  const account=await db.$transaction(tx=>saveAccount(tx,boss.token,input,"test"));
  await assert.rejects(db.$transaction(tx=>saveAccount(tx,boss.token,{...input,douyinId:marker+"bad",anchorId:anchor.id},"test")),/只能选择一种/);
  const source=await db.accountRecord.findFirstOrThrow({where:{accountId:account,endedAt:null}});
  const startedAt=new Date(Date.now()-86400000*2);startedAt.setSeconds(0,0);
  await db.accountRecord.update({where:{id:source.id},data:{startedAt:new Date(startedAt.getTime()-86400000)}});
  const create={accountId:account,externalAnchorId:ext,startedAt:shanghaiInput(startedAt),label:"外部场次"};
  await assert.rejects(db.$transaction(tx=>createDirectTask(tx,outsider.token,create,"test")),/本分公司/);
  const race=await Promise.allSettled([lead,second].map(u=>db.$transaction(tx=>createDirectTask(tx,u.token,create,"test"))));assert.equal(race.filter(r=>r.status==="fulfilled").length,1);
  const id=(race.find(r=>r.status==="fulfilled") as PromiseFulfilledResult<string>).value,task=await db.directLeadTask.findUniqueOrThrow({where:{id}}),owner=task.userId===lead.id?lead:second,notOwner=owner.id===lead.id?second:lead;
  assert.equal(await db.workSession.count({where:{accountId:account}}),0);assert.equal(await db.workShift.count({where:{userId:owner.id}}),0);
  assert.equal(await db.$transaction(tx=>readDirectTask(tx,notOwner.token,id)),null);assert.equal(await db.$transaction(tx=>readDirectTask(tx,outsider.token,id)),null);assert.equal((await db.$transaction(tx=>readDirectTask(tx,operator.token,id)))?.editable,false);
  await assert.rejects(db.$transaction(tx=>assertNoDirectDuplicate(tx,account,startedAt)),/已有直接填报/);
  const values=leadValues(Object.fromEntries(activeLeadFields.map(([key])=>[key,"0"])));Object.assign(values,{durationText:"1小时",leadMode:"yes",exposureCount:"100",entryCount:"20",peakOnline:"10",averageOnline:"5",fanGroupCount:"10",linkClickCount:"8",backendJoinCount:"5",effectiveCount:"4",femalePercent:"65.32%",age31To40Percent:"30"});
  await db.$transaction(tx=>runDirectCommand(tx,owner.token,{id,version:1,command:"save",data:values},"test"));
  await assert.rejects(db.$transaction(tx=>runDirectCommand(tx,owner.token,{id,version:1,command:"complete",data:values},"test")),/已被修改/);
  await db.$transaction(tx=>runDirectCommand(tx,owner.token,{id,version:2,command:"complete",data:values},"test"));
  const report=await db.liveReport.findUniqueOrThrow({where:{directTaskId:id}});assert.equal(report.controllerId,null);assert.equal(report.workSessionId,null);assert.equal(report.anchorId,null);assert.equal(report.externalAnchorId,ext);assert.equal(report.backendJoinCount,5);
  const list=await db.$transaction(tx=>readLeadList(tx,owner.token,"completed"));assert(list.tasks.some(t=>t.id===id&&t.direct));
  const reports=await db.$transaction(tx=>readLiveReports(tx,owner.token,{page:1,source:"direct",anchorId:`external:${ext}`,view:"monetization"}));assert.equal(reports.count,1);assert.equal(reports.summary.joins,5);assert.equal(reports.reports[0].controllerName,"未安排");
  assert.equal((await db.$transaction(tx=>readLiveReports(tx,notOwner.token,{page:1,accountId:account}))).count,0);
  await assert.rejects(db.$transaction(tx=>runDirectCommand(tx,owner.token,{id,version:3,command:"save",data:{...values,leadMode:"no"}},"test")),/更正原因/);
  await db.$transaction(tx=>runDirectCommand(tx,owner.token,{id,version:3,command:"save",reason:"不导粉更正",data:{...values,leadMode:"no"}},"test"));
  assert.equal((await db.liveReport.findUniqueOrThrow({where:{id:report.id}})).backendJoinCount,5);
  assert.equal((await db.$transaction(tx=>readLiveReports(tx,owner.token,{page:1,accountId:account,view:"monetization"}))).count,0);
  await db.$transaction(tx=>runDirectCommand(tx,owner.token,{id,version:4,command:"save",reason:"恢复导粉",data:values},"test"));
  await db.$transaction(tx=>runDirectCommand(tx,boss.token,{id,version:5,command:"delete",reason:"测试删除"},"test"));
  assert.equal((await db.$transaction(tx=>readLiveReports(tx,owner.token,{page:1,accountId:account}))).count,0);
  await assert.rejects(db.$transaction(tx=>runDirectCommand(tx,owner.token,{id,version:6,command:"save",data:values,reason:"拒绝"},"test")),/不能执行/);
  await db.$transaction(tx=>runDirectCommand(tx,boss.token,{id,version:6,command:"restore",reason:"恢复"},"test"));
  const backend=await db.$transaction(tx=>saveBackend(tx,boss.token,{name:marker+"后端",active:"true",version:0},"test"));
  const settlement={day:shanghaiInput(startedAt).slice(0,10),backendId:backend,joinCount:"5",effectiveCount:"4",backendUnit:"2.50",anchorUnit:"1.20",version:0};
  await db.$transaction(tx=>saveConfirmed(tx,boss.token,{...settlement,anchorId:`external:${ext}`},"test"));
  await db.$transaction(tx=>saveConfirmed(tx,boss.token,{...settlement,anchorId:anchor.id,joinCount:"10",effectiveCount:"8"},"test"));
  const comparison=await db.$transaction(tx=>readComparison(tx,boss.token,{from:settlement.day,to:settlement.day,anchorId:`external:${ext}`}));assert.equal(comparison.count,1);assert.equal(comparison.rows[0].reportJoins,5);assert.equal(comparison.rows[0].confirmedJoins,5);
  const income=await db.$transaction(tx=>readAnchorIncome(tx,anchor.token,{from:settlement.day,to:settlement.day}));assert.equal(income.totals.joins,10);assert.equal(income.totals.income,"9.60");
  await db.$transaction(tx=>saveExternalAnchor(tx,boss.token,{id:ext,name:"改名主播",branchId:b.id,active:"false",version:1},"test"));
  assert.equal((await db.accountRecord.findUniqueOrThrow({where:{id:source.id}})).externalAnchorName,"同名主播");assert.equal((await db.liveReport.findUniqueOrThrow({where:{id:report.id}})).anchorName,"同名主播");
  await assert.rejects(db.$transaction(tx=>createDirectTask(tx,owner.token,{...create,startedAt:shanghaiInput(new Date(+startedAt+60000))},"test")),/本分公司/);
  await assert.rejects(db.$transaction(async tx=>{await runDirectCommand(tx,owner.token,{id,version:7,command:"save",reason:"回滚验证",data:{...values,entryCount:"201"}},"test");throw new Error("forced rollback");}),/forced rollback/);
  assert.equal((await db.directLeadTask.findUniqueOrThrow({where:{id}})).version,7);
  assert.equal((await db.liveReport.findUniqueOrThrow({where:{id:report.id}})).entryCount,20);
  const preview=previewReadToken(boss.token,"leads",owner.id),sessionsBefore=await db.session.count();
  assert.equal((await db.$transaction(tx=>readLeadList(tx,preview,"completed"))).count,(await db.$transaction(tx=>readLeadList(tx,owner.token,"completed"))).count);
  await assert.rejects(db.$transaction(tx=>runDirectCommand(tx,preview,{id,version:7,command:"save",reason:"禁止",data:values},"test")),/只读预览/);
  await assert.rejects(db.$transaction(tx=>runLeadCommand(tx,preview,{id,version:0,command:"claim"},"test")),/只读预览/);
  await assert.rejects(db.$transaction(tx=>createDirectTask(tx,preview,create,"test")),/只读预览/);
  await assert.rejects(submitWorkCommand(db,preview,new FormData(),"test"),/只读预览/);
  await assert.rejects(db.$transaction(tx=>requireReadAccountActor(tx,previewReadToken(owner.token,"controller",controller.id))),/仅老板/);
  await assert.rejects(db.$transaction(tx=>requireReadAccountActor(tx,previewReadToken(boss.token,"anchor",owner.id))),/岗位状态/);
  assert.equal(await db.session.count(),sessionsBefore);
  const cp=previewReadToken(boss.token,"controller",controller.id);assert.equal((await db.$transaction(tx=>readResourceList(tx,cp,"phones","",1))).total,0);
  await assert.rejects(db.$transaction(tx=>runShiftCommand(tx,cp,{command:"begin"},"test")));
  await db.session.delete({where:{id:boss.token}});await assert.rejects(db.$transaction(tx=>requireReadAccountActor(tx,preview)),/登录或权限/);
  assert((await db.auditLog.count({where:{targetType:"DirectLeadTask",targetId:id}}))>=7);
  console.log("PASS: 外部资料与历史快照、分公司/本人权限、直接填报并发去重/草稿/提交/更正/删除恢复、无虚假场次、同名统计隔离、主播收入、只读预览权限与写拒绝");
 }finally{
  if(verified){const accounts=await db.douyinAccount.findMany({where:{douyinId:{startsWith:marker}},select:{id:true}}),ids=accounts.map(a=>a.id);await db.liveReport.deleteMany({where:{accountId:{in:ids}}});await db.directLeadTask.deleteMany({where:{accountId:{in:ids}}});await db.accountRecord.deleteMany({where:{accountId:{in:ids}}});await db.douyinAccount.deleteMany({where:{id:{in:ids}}});await db.confirmedLead.deleteMany({where:{backend:{name:{startsWith:marker}}}});await db.leadBackend.deleteMany({where:{name:{startsWith:marker}}});await db.externalAnchor.deleteMany({where:{branch:{name:{startsWith:marker}}}});await cleanupRun(db,marker);}await db.$disconnect();
 }
}
main().then(()=>console.log("ALL PASS (including cleanup)")).catch(e=>{console.error(e);process.exitCode=1;});
