import Link from "@/components/context-link";
import { bossIncome } from "@/modules/settlements/queries";
import { settlementFilters } from "@/modules/settlements/schema";
import { SettlementFilters } from "@/components/settlement-filters";
import { requireBossPage } from "@/lib/auth/permissions";
import { getWorkbench } from "@/modules/workbench/queries";
export default async function BossPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const user = await requireBossPage();
  const raw = await searchParams;
  if (!settlementFilters.safeParse(raw).success) return <p>筛选日期无效</p>;
  const [data, d] = await Promise.all([getWorkbench(), bossIncome(raw)]);
  return <><header><p className="mb-2 text-sm text-muted-foreground">你好，{user.name}</p><h1 className="text-2xl font-semibold">管理概览</h1><p className="mt-2 text-sm text-muted-foreground">统一安排账号流程、人员与物资，跟进每场直播的执行和数据。</p></header><div className="grid gap-4 sm:grid-cols-3">{[["可管理账号", data.accounts.length], ["正在直播", data.sessions.filter(s => s.phase === "LIVE").length], ["待收尾场次", data.sessions.filter(s => s.phase === "WRAP").length]].map(([label, value]) => <div key={label} className="rounded-xl border bg-white p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>)}</div><section className="space-y-4"><h2 className="text-xl font-semibold">打粉数据与总收入</h2><p className="text-sm text-muted-foreground">按已保存的确定打粉数据汇总，默认全部主播。总金额＝有效数量×后端单价；已结算表示后端已给公司结清，不代表主播提成已发放。周/月仅汇总所选日期范围内的记录。</p><SettlementFilters path="/boss" filters={d.filters} anchors={d.anchors} groups showAnchors/><div className="grid gap-4 sm:grid-cols-3">{(["income","effective"] as const).flatMap(metric=>(["all","unpaid","paid"] as const).map(status=>{const t=d.settlementTotals[status],name={all:"总打粉",unpaid:"未结算",paid:"已结算"}[status];return <Link key={`${metric}-${status}`} href={`/settlements?${new URLSearchParams({from:d.filters.from,to:d.filters.to,anchorId:d.filters.anchorId,status})}`} className="rounded-xl border bg-white p-5 hover:border-emerald-700"><p className="text-sm text-muted-foreground">{name}{metric==="income"?"金额（元）":"有效人数"}</p><p className="mt-2 text-2xl font-semibold">{t[metric]}</p>{metric==="effective"&&<p className="mt-2 text-xs text-muted-foreground">加人数量 {t.joins}</p>}</Link>;}))}</div>{d.settlementTotals.unknown.count>0&&<p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">历史待确认 {d.settlementTotals.unknown.count} 条 · 金额 ¥{d.settlementTotals.unknown.income} · 有效人数 {d.settlementTotals.unknown.effective}。总打粉包含这些记录，因此暂不等于未结算与已结算之和。<Link className="ml-2 underline" href={`/settlements?${new URLSearchParams({from:d.filters.from,to:d.filters.to,anchorId:d.filters.anchorId,status:"unknown"})}`}>核对历史记录</Link></p>}<div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{["日期 / 期间","加人数量","有效数量","总收入（元）"].map(t=><th key={t} className="p-4">{t}</th>)}</tr></thead><tbody>{d.rows.map(r=><tr key={r.period} className="border-t"><td className="p-4">{r.period}</td><td className="p-4">{r.joins}</td><td className="p-4">{r.effective}</td><td className="p-4">{r.income}</td></tr>)}{!d.rows.length&&<tr><td colSpan={4} className="p-8 text-center text-muted-foreground">所选范围暂无确定数据</td></tr>}</tbody></table></div></section></>;
}
