import { bossIncome } from "@/modules/settlements/queries";
import { settlementFilters } from "@/modules/settlements/schema";
import { SettlementFilters } from "@/components/settlement-filters";
import { requireBossPage } from "@/lib/auth/permissions";
import { getWorkbench } from "@/modules/workbench/queries";
export default async function BossPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const user = await requireBossPage();
  const raw = await searchParams;
  if (!settlementFilters.safeParse(raw).success) return <p>筛选日期无效</p>;
  const [data, d] = await Promise.all([getWorkbench(), bossIncome(raw)]);
  return <><header><p className="mb-2 text-sm text-muted-foreground">你好，{user.name}</p><h1 className="text-2xl font-semibold">管理概览</h1><p className="mt-2 text-sm text-muted-foreground">统一安排账号流程、人员与物资，跟进每场直播的执行和数据。</p></header><div className="grid gap-4 sm:grid-cols-3">{[["可管理账号", data.accounts.length], ["正在直播", data.sessions.filter(s => s.phase === "LIVE").length], ["待收尾场次", data.sessions.filter(s => s.phase === "WRAP").length]].map(([label, value]) => <div key={label} className="rounded-xl border bg-white p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>)}</div><section className="space-y-4"><h2 className="text-xl font-semibold">打粉数据与总收入</h2><p className="text-sm text-muted-foreground">按已保存的确定打粉数据汇总，默认全部主播。总收入＝有效数量×后端单价，不代表已到账。周/月仅汇总所选日期范围内的记录。</p><SettlementFilters path="/boss" filters={d.filters} anchors={d.anchors} groups showAnchors/><div className="grid gap-4 sm:grid-cols-3">{[["加人数量",d.totals.joins],["有效数量",d.totals.effective],["总收入（元）",d.totals.income]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{["日期 / 期间","加人数量","有效数量","总收入（元）"].map(t=><th key={t} className="p-4">{t}</th>)}</tr></thead><tbody>{d.rows.map(r=><tr key={r.period} className="border-t"><td className="p-4">{r.period}</td><td className="p-4">{r.joins}</td><td className="p-4">{r.effective}</td><td className="p-4">{r.income}</td></tr>)}{!d.rows.length&&<tr><td colSpan={4} className="p-8 text-center text-muted-foreground">所选范围暂无确定数据</td></tr>}</tbody></table></div></section></>;
}
