import { PhoneDirectory } from "@/components/phone-directory";
import { NumberDirectory } from "@/components/number-directory";
import Link from "@/components/context-link";
import { notFound } from "next/navigation";
import { requirePageUser, requirePasswordChanged } from "@/lib/auth/permissions";
import { listResources } from "@/modules/resources/queries";
import { pageSizeSchema, numberFiltersSchema, moneyLabel, isResourceKind, resourceLabels } from "@/modules/resources/schema";
import { AnchorDirectory } from "@/components/anchor-directory";
export default async function ResourcesPage({ params, searchParams }: { params: Promise<{ kind: string }>; searchParams: Promise<{ q?: string; page?: string; pageSize?: string; archived?: string; openedBy?: string; userId?: string; status?: string }> }) {
  const user = await requirePageUser(); await requirePasswordChanged(user);
  const { kind } = await params; if (kind === "anchors") return <AnchorDirectory />; if (!isResourceKind(kind)) notFound();
  const search = await searchParams, q = typeof search.q === "string" ? search.q.trim().slice(0, 100) : "", page = Math.max(1, Math.min(100000, Math.trunc(Number(search.page) || 1)));
  if (kind === "numbers") {
    const parsed = numberFiltersSchema.safeParse({ openedBy: search.openedBy, userId: search.userId, status: search.status });
    return <NumberDirectory q={q} page={page} pageSize={pageSizeSchema.parse(search.pageSize)} filters={parsed.success ? parsed.data : {}} />;
  }
  if (kind === "phones") return <PhoneDirectory q={q} page={page} pageSize={pageSizeSchema.parse(search.pageSize)} userId={typeof search.userId === "string" ? search.userId.slice(0,100) : ""} status={typeof search.status === "string" ? search.status : ""} />;
  const isAsset = kind !== "rooms";
  const archived = kind === "materials" && search.archived === "true";
  const { rows, manager, total, page: actualPage, pages } = await listResources(kind, q, page, archived);
  return <><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">{resourceLabels[kind]}管理</h1>{manager && <Link className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground" href={`/resources/${kind}/new`}>新增{resourceLabels[kind]}</Link>}</header><p className="text-sm text-muted-foreground">按分公司和负责关系展示资料；点击名称或编号查看关联信息。</p>{kind === "materials" && <nav className="flex gap-4 text-sm"><Link href="?">现有物资</Link><Link href="?archived=true">已拆分批次（不计存量）</Link></nav>}{archived && <p className="text-sm text-amber-700">此处为拆分来源，只保留原始批次信息，不重复计入现有数量和资产价值。</p>}<form method="GET" className="flex gap-2">{archived && <input type="hidden" name="archived" value="true" />}<input name="q" defaultValue={q} maxLength={100} placeholder={`搜索${resourceLabels[kind]}名称、号码或编号`} aria-label="搜索" className="w-full max-w-sm rounded-lg border px-3 py-2 text-sm" /><button className="rounded-lg border px-4 py-2 text-sm">搜索</button></form>
    <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/50"><tr>{[resourceLabels[kind], kind === "rooms" ? "主播" : "信息", "分公司", ...(kind === "rooms" ? [] : ["直播间"]), "运营", "直播中控", ...(kind === "rooms" ? [] : ["使用人"]), ...(isAsset ? ["数量", "购入单价", "购入总额", "单件估值", "估值总额"] : []), "状态"].map(h => <th key={h} className="whitespace-nowrap px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(r => { const asset = "asset" in r ? r.asset : null; return <tr key={r.id} className="border-t"><td className="whitespace-nowrap px-4 py-4"><Link href={`/resources/${kind}/${r.id}`} className="font-medium text-primary underline">{r.title}</Link></td><td className="min-w-40 px-4 py-4">{r.description || "—"}</td><td className="whitespace-nowrap px-4 py-4">{r.branch}</td>{kind !== "rooms" && <td className="px-4 py-4">{r.room ?? "暂未分配"}</td>}<td className="px-4 py-4">{r.operator ?? "未分配"}</td><td className="px-4 py-4">{r.controller ?? "未分配"}</td>{kind !== "rooms" && <td className="px-4 py-4">{r.user ?? "未分配"}</td>}{isAsset && <>{[asset?.quantity === null || !asset ? "未登记" : `${asset.quantity} ${asset.unit}`, moneyLabel(asset?.purchaseUnitPriceCents ?? null), moneyLabel(asset?.quantity != null && asset.purchaseUnitPriceCents !== null ? asset.quantity * asset.purchaseUnitPriceCents : null), moneyLabel(asset?.currentUnitValueCents ?? null), moneyLabel(asset?.quantity != null && asset.currentUnitValueCents !== null ? asset.quantity * asset.currentUnitValueCents : null)].map((value, i) => <td key={i} className="whitespace-nowrap px-4 py-4">{value}</td>)}</>}<td className="px-4 py-4">{archived ? "已拆分" : r.active ? "启用" : "停用"}</td></tr>; })}</tbody></table>{!rows.length && <p className="p-8 text-center text-sm text-muted-foreground">暂无符合条件的资料</p>}</div><nav className="flex gap-4 text-sm">{actualPage > 1 && <Link href={`?q=${encodeURIComponent(q)}&archived=${archived}&page=${actualPage - 1}`}>上一页</Link>}<span>共 {total} 条 · 第 {actualPage} / {pages} 页</span>{actualPage < pages && <Link href={`?q=${encodeURIComponent(q)}&archived=${archived}&page=${actualPage + 1}`}>下一页</Link>}</nav>
  </>;
}
