import Link from "@/components/context-link";
import { requirePageUser, requirePasswordChanged } from "@/lib/auth/permissions";
import { getLeadList } from "@/modules/leads/queries";
import { formatDateTime } from "@/lib/datetime";
export default async function LeadsPage({ searchParams }: { searchParams: Promise<{ view?: string; page?: string }> }) {
  const user = await requirePageUser(); await requirePasswordChanged(user);
  const params = await searchParams;
  const view = ["available", "completed", "trash"].includes(params.view ?? "") ? params.view! : "work";
  const page = Math.max(1, Math.min(100000, Math.floor(Number(params.page) || 1)));
  const data = await getLeadList(view, page);
  const title = view === "available" ? "可认领场次" : view === "completed" ? "已完成场次" : view === "trash" ? "回收站" : "已认领待完成";
  return <><header className="space-y-2"><h1 className="text-2xl font-semibold">{title}</h1><p className="text-sm text-slate-500">{view === "available" ? "仅显示新流程启用后已实际开播、尚未认领的本分公司场次。可以同时负责多场，先确认实际导粉人员再认领，未提交完成可撤销误认领。" : "每场独立填写直播数据和打粉数据，未确定的内容可以跨天补填。"}</p></header>{data.specialist && <Link href="/leads/direct/new" className="inline-block rounded-lg bg-emerald-900 px-4 py-2 text-sm text-white">直接录入场次数据</Link>}<nav className="flex flex-wrap gap-5 border-b pb-4 text-sm">{data.specialist && <Link href="/leads?view=available">可认领场次</Link>}<Link href="/leads">{"已认领待完成"}</Link><Link href="/leads?view=completed">已完成场次</Link><Link className="ml-auto text-xs text-slate-500" href="/leads?view=trash" aria-label="回收站（次要入口）">回收站</Link></nav>
    <div className="grid gap-4 xl:grid-cols-2">{data.sessions.map(s => <section key={s.id} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">{s.sourceRecord.name} · {s.label}</h2><p className="text-sm">{s.sourceRecord.branchName} · 主播 {s.sourceRecord.anchorName ?? "未记录"} · 直播间 {s.account.room?.name ?? "未分配"}</p><p className="text-sm text-slate-500">{formatDateTime(s.startedAt!)} 开播 · {s.phase === "LIVE" ? "正在直播" : "已下播"} · 未认领</p><Link href={`/leads/claim/${s.id}`} className="inline-block rounded-lg bg-emerald-900 px-4 py-2 text-sm text-white">选择本场</Link></section>)}
    {data.tasks.map(t => <Link key={t.id} href={t.direct?`/leads/direct/${t.id}`:`/leads/${t.id}`} className="space-y-3 rounded-xl border bg-white p-5 hover:border-emerald-800"><h2 className="font-semibold">{t.direct && <span className="mr-2 text-xs text-emerald-800">直接录入</span>}{t.session.sourceRecord.name} · {t.session.label}</h2><p className="text-sm">导粉专员：{t.userName} · 主播：{t.session.sourceRecord.anchorName ?? "未记录"}</p><p className="text-sm text-slate-500">{formatDateTime(t.session.startedAt!)} 开播</p><p className="text-sm font-medium">{t.deletedAt ? "已移入回收站" : t.completedAt ? "数据已完成" : t.direct ? "待填报" : t.session.phase === "LIVE" ? "正在直播" : `待补数据 · 已下播 ${Math.max(0, Math.floor((data.asOf - (t.session.endedAt?.getTime() ?? data.asOf)) / 60000))} 分钟`} →</p></Link>)}</div>
    {!data.count && <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">暂无{title}</p>}<nav className="flex justify-between text-sm">{page > 1 ? <Link href={`/leads?view=${view}&page=${page - 1}`}>上一页</Link> : <span />}<span>共 {data.count} 场 · 第 {page} 页</span>{page * 20 < data.count && <Link href={`/leads?view=${view}&page=${page + 1}`}>下一页</Link>}</nav></>;
}
